### ISSUE TITLE
11.3 (Matrix factorization by iterative Greedy Minimization)

### ISSUE THREAD

**Issue by kilianrisse** [mohlerm/eth-cil-exam-summary#10]
Coding Step and Dictionary update step in more detail; how it can be computed if space permits it.

**Comment by mohlerm** [comment]
There is a bit space left, do you want to extent it a bit?

**Comment by Robin-des-Bois** [comment]
Isn't the coding step just matching pursuit? But I agree that some formula for the dictionary update step would be nice!
