### ISSUE TITLE
K-means stopping condition

### ISSUE THREAD

**Issue by jonaspu** [mohlerm/eth-cil-exam-summary#13]
Not sure if the condition on the summary is equivalent, but in the slides the k-means stopping condition is given by:

![image](https://cloud.githubusercontent.com/assets/6840940/17649287/67c2a46a-6231-11e6-9bda-af692dd22a2d.png)

Whereas in the summary it states:

![image](https://cloud.githubusercontent.com/assets/6840940/17649292/795d0d28-6231-11e6-9557-05e7163d06ff.png)

**Comment by kilianrisse** [comment]
As the differences are always 0 or 1, it is actually equal. But I think it is confusing too. I will change it. Thanks!
