### ISSUE TITLE
[Addition] 4. K-means: Clustering Stability

### ISSUE THREAD

**Issue by passuf** [mohlerm/eth-cil-exam-summary#3]
In lecture 4 we also discussed clustering stability, including:
- Distance between clusters
- Calculation of stability
- Normalization of stability

We could consider adding those formulas to the summary, but I am not sure if this is relevant or if we have enough space. I can make a pull request if there is nothing more important we can add.

**Comment by mohlerm** [comment]
Thanks, that is definitely something to consider.
Let us wait and see if more important topics arise and include it later if the space remains unneeded.

**Comment by mohlerm** [comment]
I think we should include this, I'll add it later.
