### ISSUE TITLE
Sparse Coding

### ISSUE THREAD

**Issue by kilianrisse** [mohlerm/eth-cil-exam-summary#9]
There is not a lot about it; things one could add:

.difference haar/fourier (in general that different bases needed for different signals)
.advantage/disadvantage PCA vs fixed basis
.overcomplete dicts and their advantages, disadvantages (mainly inversion)
.noisy observations?

What do we need?

**Comment by mohlerm** [comment]
I plan to go over this lecture again today and will post my opinions later.

**Comment by kilianrisse** [comment]
Further I think it would make sense to make 3 subsections 'orthogonal basis' and  'overcomplete basis' and 'dictionary learning'. Further move the MP algorithm into overcomplete basis along with the subsection about compressive sensing. And I think we could add a section about advantages/disadvantages about each.

**Comment by kilianrisse** [comment]
(this would get rid of the section 'dictionary learning' as this is one way to do sparse encoding)

**Comment by mohlerm** [comment]
Well, I kind of wanted the sections to represent the lecture but in general I think these are good suggestions, there are definitely some things missing in 'Sparse coding'
